apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ .Values.appName }}
    version: {{ .Values.version}}
spec:
  type: NodePort
  ports:
  - name: https
    port: 8443
    protocol: TCP
    nodePort: {{ .Values.nodePort}}
  selector:
    app: {{ .Values.appName }}
    version: {{ .Values.version}}
